"""
Your task is to update the code so that,
instead of printing every event, you only
print the text deltas from the agent’s response as they arrive.

Here’s what you need to do:

In your async for loop over result.stream_events(),
check if the event is a "raw_response_event" and its data is a ResponseTextDeltaEvent.
If so, print the value of event.data.delta using print(event.data.delta, end="", flush=True).
This will help you see just the new text generated by the agent, as it becomes available.
"""

import asyncio
from agents import Agent, Runner
from openai.types.responses import ResponseTextDeltaEvent

# Define the agent
agent = Agent(
    name="Travel Genie",
    instructions=(
        "You are Travel Genie, a friendly and knowledgeable travel assistant. "
        "Recommend exciting destinations and offer helpful travel tips."
    ),
    model="gpt-4.1"
)


async def main():
    # Run the agent in streaming mode
    result = Runner.run_streamed(
        starting_agent=agent,
        input="What are the best travel tips for solo travelers in Japan?",
    )

    # Process streaming events
    async for event in result.stream_events():
    # TODO: Check if the event is a "raw_response_event" and its data is a ResponseTextDeltaEvent
        # If so, print the value of event.data.delta using end="" and flush=True
        if event.type == "raw_response_event" and  isinstance(event.data, ResponseTextDeltaEvent):
            print(event.data.delta, end="", flush=True)

if __name__ == "__main__":
    asyncio.run(main())